spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000ms # 连接超时时间
    database: 0 # Redis数据库索引（默认为0）
    jedis:
      pool:
        max-active:
  data:
    redis:
      repositories:
        enabled: true



    
