server:
  port: 8082
spring:
  data:
    mongodb:
      port: 27017
      host: 127.0.0
      database: test
      


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
