server:
  port: 8082

spring:
  elasticsearch:
    rest:
      uris: http://192.168.0.105:9200
      username:
      password:



#开启elasticsearch的日志打印
logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            core: DEBUG
    #打印出完整的curl语句以及完整的json
    tracer: TRACE






